package com.aihotradar.coreapi.admin;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.UUID;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Component;

/**
 * Resolves a bearer token to a principal, and bootstraps the first credential.
 *
 * <p>Tokens are stored as SHA-256 hex and the lookup is by hash, so the plaintext exists only for
 * the life of a request and never reaches the database, a log or an index. Looking up <em>by</em>
 * the hash rather than fetching a row and comparing also removes the question of constant-time
 * comparison entirely: there is nothing in application code to time.
 *
 * <p>SHA-256 rather than bcrypt/argon2 on purpose. Those exist to survive an offline attack on a
 * <em>low-entropy human-chosen</em> secret. This credential is a random 32-byte value generated by
 * the operator, so there is no dictionary to run and the stretching would buy nothing while costing
 * a hash on every admin request. That reasoning stops holding the moment anyone types a memorable
 * token, which is why {@link #BOOTSTRAP_MIN_LENGTH} refuses short ones.
 */
@Component
public class AdminTokens {

    private static final Logger log = LoggerFactory.getLogger(AdminTokens.class);

    /**
     * Short enough to be memorable is short enough to be guessed, and the hashing choice above
     * assumes it is not. 32 characters is the shortest that keeps that assumption honest.
     */
    static final int BOOTSTRAP_MIN_LENGTH = 32;

    private final NamedParameterJdbcTemplate jdbc;
    private final String bootstrapToken;
    private final String viewerToken;

    public AdminTokens(
            NamedParameterJdbcTemplate jdbc,
            @Value("${ahr.admin.bootstrap-token:}") String bootstrapToken,
            @Value("${ahr.admin.viewer-token:}") String viewerToken) {
        this.jdbc = jdbc;
        this.bootstrapToken = bootstrapToken == null ? "" : bootstrapToken.trim();
        this.viewerToken = viewerToken == null ? "" : viewerToken.trim();
    }

    /** Lowercase SHA-256 hex. Package-private so the tests can pin the exact encoding. */
    static String hash(String token) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            return HexFormat.of()
                    .formatHex(digest.digest(token.getBytes(StandardCharsets.UTF_8)));
        } catch (NoSuchAlgorithmException e) {
            // SHA-256 is mandated by the platform; if it is missing, failing closed is the only
            // safe response.
            throw new IllegalStateException("SHA-256 unavailable", e);
        }
    }

    /**
     * The principal for this token, or empty if there is none.
     *
     * <p>Empty covers every failure the caller is allowed to distinguish: unknown token, revoked
     * credential, and a role the code does not recognise. Telling them apart in the response would
     * confirm which tokens exist.
     */
    public Optional<AdminPrincipal> resolve(String token) {
        if (token == null || token.isBlank()) {
            return Optional.empty();
        }
        List<AdminPrincipal> found =
                jdbc.query(
                        """
                        SELECT id, label, role FROM admin_principal
                         WHERE token_hash = :hash AND disabled_at IS NULL
                        """,
                        new MapSqlParameterSource("hash", hash(token)),
                        (rs, rowNum) -> {
                            AdminRole role = AdminRole.parse(rs.getString("role")).orElse(null);
                            return role == null
                                    ? null
                                    : new AdminPrincipal(
                                            rs.getObject("id", UUID.class),
                                            rs.getString("label"),
                                            role);
                        });
        return found.stream().filter(Objects::nonNull).findFirst();
    }

    /** Records that a credential was used, for deciding which ones are dead and can be revoked. */
    public void touch(UUID principalId) {
        jdbc.update(
                "UPDATE admin_principal SET last_used_at = now() WHERE id = :id",
                new MapSqlParameterSource("id", principalId));
    }

    /**
     * Registers the configured credentials if they are not already registered.
     *
     * <p>Called at startup. An unset variable creates nothing, so the admin API stays closed to
     * everything — the correct default for a service reachable from the internet: the failure mode
     * of a missing secret is a locked door, not an open one.
     *
     * <p>Idempotent by token hash, so restarting does not accumulate rows, and rotating means
     * changing the variable and revoking the old row.
     */
    public void bootstrap() {
        register(bootstrapToken, "bootstrap", AdminRole.OPERATOR);
        // The web tier's own credential. It renders the source console during SSR and never
        // mutates, so it gets a role that cannot: a compromised web container then cannot disable
        // a source, which is the difference between least privilege as a property and as a word.
        register(viewerToken, "web", AdminRole.VIEWER);
    }

    private void register(String token, String label, AdminRole role) {
        if (token.isEmpty()) {
            log.info("no admin token configured for '{}'; that credential will not exist", label);
            return;
        }
        if (token.length() < BOOTSTRAP_MIN_LENGTH) {
            // Refused rather than accepted-with-a-warning: a warning in a startup log is not a
            // control, and this one guards the assumption that makes plain SHA-256 adequate.
            throw new IllegalStateException(
                    "admin token '"
                            + label
                            + "' must be at least "
                            + BOOTSTRAP_MIN_LENGTH
                            + " characters; generate one with `openssl rand -hex 32`");
        }
        int inserted =
                jdbc.update(
                        """
                        INSERT INTO admin_principal (label, token_hash, role)
                        VALUES (:label, :hash, :role)
                        ON CONFLICT (token_hash) DO NOTHING
                        """,
                        new MapSqlParameterSource()
                                .addValue("label", label)
                                .addValue("hash", hash(token))
                                .addValue("role", role.name()));
        if (inserted > 0) {
            log.info("registered admin credential '{}' as {}", label, role);
        }
    }
}
