import Link from "next/link";
import { notFound } from "next/navigation";

import { REPORT_PERIODS, fetchReport, formatPeriodKey, normalisePeriod } from "@/lib/api";

export const dynamic = "force-dynamic";

/**
 * Minimal markdown rendering for the report body.
 *
 * The body is generated by our own pipeline from a fixed template, so the shape
 * is known. It is still rendered as structured elements rather than injected as
 * HTML: AHR-QSO-700 §3 forbids raw injection, and the item titles inside come
 * from third-party sources.
 */
function renderMarkdown(markdown: string) {
  const linkPattern = /^- \*\*\[(.+?)\]\((.+?)\)\*\* · (.+)$/;

  return markdown.split("\n").map((line, index) => {
    const key = `${index}-${line.slice(0, 12)}`;

    if (line.startsWith("# ")) return null; // page title already shows this
    if (line.startsWith("## ")) {
      return (
        <h2 key={key} className="day-heading">
          {line.slice(3)}
        </h2>
      );
    }
    if (line.startsWith("---")) {
      return (
        <hr
          key={key}
          style={{ border: 0, borderTop: "1px solid var(--border)", margin: "20px 0" }}
        />
      );
    }

    const match = linkPattern.exec(line);
    if (match) {
      const [, title, url, source] = match;
      return (
        <p key={key} style={{ margin: "10px 0 2px" }}>
          <a href={url} target="_blank" rel="noreferrer noopener" style={{ fontWeight: 600 }}>
            {title} ↗
          </a>
          <span style={{ color: "var(--muted)", fontSize: 12, marginLeft: 8 }}>{source}</span>
        </p>
      );
    }

    if (line.startsWith("  ")) {
      return (
        <p key={key} style={{ margin: "0 0 8px", fontSize: 13, color: "#43433f" }}>
          {line.trim()}
        </p>
      );
    }
    if (!line.trim()) return null;

    return (
      <p key={key} style={{ margin: "0 0 12px" }}>
        {line}
      </p>
    );
  });
}

export default async function ReportPage({
  params,
}: {
  params: Promise<{ period: string; key: string }>;
}) {
  const raw = await params;
  const period = normalisePeriod(raw.period);

  // An unrecognised period would otherwise silently fall back to daily and show
  // the wrong report under a URL that claims to be weekly.
  if (raw.period !== period) {
    notFound();
  }

  const report = await fetchReport(period, raw.key);
  if (!report) {
    notFound();
  }

  const label = REPORT_PERIODS.find((entry) => entry.key === period)?.label ?? "报告";

  return (
    <>
      <p className="page-subtitle">
        <Link href={period === "daily" ? "/reports" : `/reports?period=${period}`}>
          ← 返回{label}列表
        </Link>
      </p>

      <h1 className="page-title">{report.title}</h1>
      <p className="page-subtitle">
        {formatPeriodKey(period, report.date)} · {report.itemCount} 条精选
        {report.modelName ? ` · 总述由 ${report.modelName} 生成` : ""}
        {report.promptVersion ? ` · ${report.promptVersion}` : ""}
      </p>

      <div className="detail-body">{renderMarkdown(report.bodyMarkdown)}</div>

      <div className="notice">
        {label}总述为 AI 生成内容，可能存在误差。每条目均链接到原始来源，事实请以原文为准。
      </div>
    </>
  );
}
